# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('power', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=1)),
                ('eq_type', models.CharField(max_length=1)),
                ('level', models.IntegerField(default=1)),
                ('dexterity', models.IntegerField(default=0)),
                ('endurance', models.IntegerField()),
                ('speed', models.IntegerField(default=0)),
                ('poison', models.IntegerField(default=0)),
                ('max_endurance', models.IntegerField()),
                ('repair', models.IntegerField()),
                ('two_handed', models.BooleanField(default=False)),
                ('cost', models.IntegerField()),
                ('shop', models.BooleanField(default=False)),
                ('magic', models.BooleanField(default=False)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
