# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='eq_type',
            field=models.CharField(max_length=15),
        ),
    ]
