# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import players.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=20, verbose_name='first name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'player',
                'abstract': False,
                'verbose_name_plural': 'players',
            },
            managers=[
                ('objects', players.models.PlayerManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
