# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20160215_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerReligion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='ap',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='player',
            name='bank_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='coins',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='energy',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='player',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='hp',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='player',
            name='last_killed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_killed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_kills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='logins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='max_energy',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='player',
            name='max_hp',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='player',
            name='sex',
            field=models.CharField(default='man', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.PlayerClass'),
        ),
        migrations.AddField(
            model_name='player',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.PlayerRace'),
        ),
        migrations.AddField(
            model_name='player',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.PlayerReligion'),
        ),
    ]
