# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20160215_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacksmithing', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alchemy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wood_working', models.DecimalField(decimal_places=2, max_digits=6)),
                ('archery', models.DecimalField(decimal_places=2, max_digits=6)),
                ('evasion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mining', models.DecimalField(decimal_places=2, max_digits=6)),
                ('herbalism', models.DecimalField(decimal_places=2, max_digits=6)),
                ('jewellery', models.DecimalField(decimal_places=2, max_digits=6)),
                ('metallurgy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('spell_casting', models.DecimalField(decimal_places=2, max_digits=6)),
                ('leadership', models.DecimalField(decimal_places=2, max_digits=6)),
                ('breeding', models.DecimalField(decimal_places=2, max_digits=6)),
                ('melee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('perceptivity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
