# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 23:18
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20160215_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dexterity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.01000000000000000020816681711721685132943093776702880859375'), max_digits=7),
        ),
        migrations.AddField(
            model_name='player',
            name='endurance',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.01000000000000000020816681711721685132943093776702880859375'), max_digits=7),
        ),
        migrations.AddField(
            model_name='player',
            name='inteligence',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.01000000000000000020816681711721685132943093776702880859375'), max_digits=7),
        ),
        migrations.AddField(
            model_name='player',
            name='magic_points',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='player',
            name='max_magic_points',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='player',
            name='religion_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='speed',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.01000000000000000020816681711721685132943093776702880859375'), max_digits=7),
        ),
        migrations.AddField(
            model_name='player',
            name='strength',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.01000000000000000020816681711721685132943093776702880859375'), max_digits=7),
        ),
        migrations.AddField(
            model_name='player',
            name='willpower',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.01000000000000000020816681711721685132943093776702880859375'), max_digits=7),
        ),
    ]
