# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_playerskills_carpentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 16, 20, 55, 50, 919821, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
